version: '3.7'
services:

  # MariaDB service
  MariaDB:
    container_name: "MariaDB"
    image: mariadb:latest
    volumes:
        - "./dockerData/mariadb:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVICE_NAME: mariadb
      SERVICE_TAG: dev
    ports:
      - 3366:3306
    networks:
      - MariaDB

  # PHP Service
  php:
    build:
      context: ./dockerImages/php
    ports:
    - 8080:80
    - 1443:443
    - 9001:9001
    volumes:
      - ./:/var/www/sdocker
      - ./dockerData/logs/symfony:/var/www/sdocker/app/logs
    depends_on:
      - MariaDB
    networks:
      - MariaDB
      - php

#Docker Networks
networks:
  MariaDB:
  php: