version: '3.7'
services:

  # MariaDB service
  MariaDB:
    container_name: "MariaDB"
    image: mariadb:latest
    volumes:
        - "./dockerData/mariadb:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVICE_NAME: mariadb
      SERVICE_TAG: dev
    ports:
      - 3366:3306
    networks:
      - MariaDB

  # PHP Service
  php:
    build:
      context: ./dockerImages/php
    ports:
    - 8080:80
    - 1443:443
    - 9001:9001
    volumes:
      - ./:/var/www/sdocker
      - ./dockerData/logs/symfony:/var/www/sdocker/var/log
      - ./dockerData/logs/nginx:/var/log/nginx
    depends_on:
      - MariaDB
    networks:
      - MariaDB
      - php
  elk:
    build:
      context: ./dockerImages/elk
    ports:
      - 8181:80
    volumes:
      - ./dockerImages/elk/logstash/:/etc/logstash
      - ./dockerImages/elk/logstash/patterns:/etc/logstash/patterns
   # volumes_from:
    #  - php
     # - MariaDB

#Docker Networks
networks:
  MariaDB:
  php: